//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Riccardos77.AppConfig.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Riccardos77.AppConfig.Api.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;#schemaId#&quot;,
        ///  &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;$schema&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///    &quot;appIdentities&quot;: {
        ///      &quot;type&quot;: &quot;object&quot;,
        ///      &quot;additionalProperties&quot;: {
        ///        &quot;type&quot;: &quot;object&quot;,
        ///        &quot;properties&quot;: {
        ///          &quot;appIdentityId&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///          &quot;aadApplicationId&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///          &quot;displayName&quot;: { &quot;type&quot;: &quot;string&quot; }
        ///        },
        ///        &quot;additionalProperties&quot;: false
        ///      }
        ///    },
        ///    &quot;tags&quot;: {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppMetaschemaSchema {
            get {
                return ResourceManager.GetString("AppMetaschemaSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;id&quot;: &quot;#schemaId#&quot;,
        ///  &quot;$schema&quot;: &quot;https://json-schema.org/draft-04/schema&quot;,
        ///  &quot;type&quot;: &quot;object&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;origin&quot;: { &quot;$ref&quot;: &quot;#/definitions/origin&quot; },
        ///    &quot;json2ts&quot;: { &quot;$ref&quot;: &quot;#/definitions/json2ts&quot; }
        ///  },
        ///  &quot;definitions&quot;: {
        ///    &quot;origin&quot;: {
        ///      &quot;type&quot;: &quot;object&quot;,
        ///      &quot;properties&quot;: {
        ///        &quot;configInstanceUrl&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///        &quot;appName&quot;: { &quot;type&quot;: &quot;string&quot; },
        ///        &quot;appIdentity&quot;: { &quot;type&quot;: &quot;string&quot; }
        ///      },
        ///      &quot;required&quot;: [&quot;configInstanceUrl&quot;, &quot;appNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConfigCliSchema {
            get {
                return ResourceManager.GetString("ConfigCliSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;id&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;$schema&quot;: &quot;http://json-schema.org/draft-04/schema#&quot;,
        ///    &quot;description&quot;: &quot;Core schema meta-schema&quot;,
        ///    &quot;definitions&quot;: {
        ///        &quot;schemaArray&quot;: {
        ///            &quot;type&quot;: &quot;array&quot;,
        ///            &quot;minItems&quot;: 1,
        ///            &quot;items&quot;: { &quot;$ref&quot;: &quot;#&quot; }
        ///        },
        ///        &quot;positiveInteger&quot;: {
        ///            &quot;type&quot;: &quot;integer&quot;,
        ///            &quot;minimum&quot;: 0
        ///        },
        ///        &quot;positiveIntegerDefault0&quot;: {
        ///            &quot;allOf&quot;: [ { &quot;$ref&quot;: &quot;#/definitions/positiveInteger&quot; }, {  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JsonDraft04Schema {
            get {
                return ResourceManager.GetString("JsonDraft04Schema", resourceCulture);
            }
        }
    }
}
