apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app-config.fullname" . }}-env-cm
  labels:
    {{- include "app-config.labels" . | nindent 4 }}
data:
 {{- tpl (toYaml .Values.envFrom) . | nindent 2 }}
