# yaml-language-server: $schema=values-schema.json
global:
  # -- docker registry url
  repository: privaterepo.azurecr.io/

fullnameOverride: test-parent-chart

appconfig:
  fullnameOverride: appconfig-in-test

  envFrom:
    AppCatalog__booking-booking-ri__IdentityKeys__booking-app: 1203E20F-B642-4D55-9F58-9719FEFCFC2B
    AppCatalog__booking-booking-ri__DataProvider__FileSystem__RootPath: /etc/config/booking-booking-ri
    #Logging__LogLevel__Microsoft.AspNetCore: Debug

  configMapRefs:
    - objectName: test-parent-chart-config2
      volumeName: vol
      mountPath: /etc/config2
      readOnly: true
