{{ $objectName := include "helm-utility-lib.helpers.objectName" (merge (dict "suffix" "-config2") .) }}
{{ $args := dict "objectName" $objectName "contentFormat" "text" "filesGlob" "files/config2/**.*" }}
{{ include "helm-utility-lib.components.configmap-files" (merge $args .) }}
