# yaml-language-server: $schema=values.schema.json

replicaCount: 1

image:
  imageName: riccardos77/app-config
  repository: docker.io/
  tag: 0.3.0
  pullPolicy: IfNotPresent

restartPolicy: Always
dnsPolicy: ClusterFirst

fullnameOverride: "riccardos77-app-config"

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # PROVIDE REASONABLE VALUES FOR REQUESTS AND LIMITS BASED ON APP REQUIREMENT
  # DON'T PUT DEFAULT OR MINIMAL IN PARTICULAR ON REQUESTS.
  requests:
    cpu: "20m"
    memory: "128Mi"
  limits:
    cpu: "20m"
    memory: "128Mi"

livenessProbe:
  enabled: false
  httpGet:
    path: /liveness
    port: 2113
    scheme: HTTP
  initialDelaySeconds: 2
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 1

readinessProbe:
  enabled: true
  httpGet:
    path: /readiness
    port: 2113
    scheme: HTTP
  initialDelaySeconds: 5
  periodSeconds: 30
  successThreshold: 1
  failureThreshold: 3
  timeoutSeconds: 5

# Append additional Environment variables
# NB: change to the following section will trigger pod restart
envFrom:
  ASPNETCORE_ENVIRONMENT: DevContainer
  ASPNETCORE_URLS: http://*:8080;http://*:2113

service:
  enabled: true
  type: ClusterIP
  port:
    port: 8080
    protocol: TCP
    targetPort: http
    name: http
  containerPort: 8080

containerPorts:
  - containerPort: 2113
    name: health
    protocol: TCP
